export const PUBLIC_EC2_ADD = 'http://34.235.87.16:8888'
export const HOST_AWS = 'https://bu1ik0gj36.execute-api.us-east-1.amazonaws.com'
export const ENDPOINT_AWS = process.env.NEXT_PUBLIC_ENDPOINT_AWS || 'null-or-undefined-endpoint'
export const ACCESS_KEY_AWS = process.env.NEXT_PUBLIC_ACCESS_KEY_AWS ||'null-or-undefined-access-key'
export const SECRET_KEY_AWS = process.env.NEXT_PUBLIC_SECRET_KEY_AWS || 'null-or-undefined-secret-key'
export const SESSION_TOKEN_AWS = process.env.NEXT_PUBLIC_SESSION_TOKEN_AWS || 'null-or-undefined-session-token'